name: Test GitHub Secrets

on:
  push:
    branches:
      - main

jobs:
  print-secrets:
    runs-on: ubuntu-latest

    steps:
      - name: Echo masked secret (they are always masked!)
        run: echo "MY_SECRET_KEY is: ${{ secrets.MY_SECRET_KEY }}"

      - name: Echo a varaibles
        run: echo "MY_VAR is: ${{ vars.MY_VAR }}"
